export const PAYMENTS_REQUEST = "PAYMENTS_REQUEST";
export const PAYMENTS_SUCCESS = "PAYMENTS_SUCCESS";
export const PAYMENTS_FAIL = "PAYMENTS_FAIL";

export const INCOME_REQUEST = "INCOME_REQUEST";
export const INCOME_SUCCESS = "INCOME_SUCCESS";
export const INCOME_FAIL = "INCOME_FAIL";

export const PAYMENTS_ADD_REQUEST = "PAYMENTS_ADD_REQUEST";
export const PAYMENTS_ADD_SUCCESS = "PAYMENTS_ADD_SUCCESS";
export const PAYMENTS_ADD_FAIL = "PAYMENTS_ADD_FAIL";

export const INCOME_ADD_REQUEST = "INCOME_ADD_REQUEST";
export const INCOME_ADD_SUCCESS = "INCOME_ADD_SUCCESS";
export const INCOME_ADD_FAIL = "INCOME_ADD_FAIL";

export const PAYMENTS_DELETE_REQUEST = "PAYMENTS_DELETE_REQUEST";
export const PAYMENTS_DELETE_SUCCESS = "PAYMENTS_DELETE_SUCCESS";
export const PAYMENTS_DELETE_FAIL = "PAYMENTS_DELETE_FAIL";

export const INCOME_DELETE_REQUEST = "INCOME_DELETE_REQUEST";
export const INCOME_DELETE_SUCCESS = "INCOME_DELETE_SUCCESS";
export const INCOME_DELETE_FAIL = "INCOME_DELETE_FAIL";

export const PAYMENTS_RENAME_REQUEST = "PAYMENTS_RENAME_REQUEST";
export const PAYMENTS_RENAME_SUCCESS = "PAYMENTS_RENAME_SUCCESS";
export const PAYMENTS_RENAME_FAIL = "PAYMENTS_RENAME_FAIL";

export const INCOME_RENAME_REQUEST = "INCOME_RENAME_REQUEST";
export const INCOME_RENAME_SUCCESS = "INCOME_RENAME_SUCCESS";
export const INCOME_RENAME_FAIL = "INCOME_RENAME_FAIL";
