export const FETCH_DATES_REQUEST = "FETCH_DATES_REQUEST";
export const FETCH_DATES_SUCCESS = "FETCH_DATES_SUCCESS";
export const FETCH_DATES_FAIL = "FETCH_DATES_FAIL";

export const FETCH_DATA_FOR_CHARTS_REQUEST = "FETCH_DATA_FOR_CHARTS_REQUEST";
export const FETCH_DATA_FOR_CHARTS_SUCCESS = "FETCH_DATA_FOR_CHARTS_SUCCESS";
export const FETCH_DATA_FOR_CHARTS_FAIL = "FETCH_DATA_FOR_CHARTS_FAIL";
