export const INCOME_VALUES_REQUEST = "INCOME_VALUES_REQUEST";
export const INCOME_VALUES_SUCCESS = "INCOME_VALUES_SUCCESS";
export const INCOME_VALUES_FAIL = "INCOME_VALUES_FAIL";

export const INCOME_ADD_VALUES_REQUEST = "INCOME_ADD_VALUES_REQUEST";
export const INCOME_ADD_VALUES_SUCCESS = "INCOME_ADD_VALUES_SUCCESS";
export const INCOME_ADD_VALUES_FAIL = "INCOME_ADD_VALUES_FAIL";
