export const PAYMENTS_VALUES_REQUEST = "PAYMENTS_VALUES_REQUEST";
export const PAYMENTS_VALUES_SUCCESS = "PAYMENTS_VALUES_SUCCESS";
export const PAYMENTS_VALUES_FAIL = "PAYMENTS_VALUES_FAIL";

export const PAYMENTS_ADD_VALUES_REQUEST = "PAYMENTS_ADD_VALUES_REQUEST";
export const PAYMENTS_ADD_VALUES_SUCCESS = "PAYMENTS_ADD_VALUES_SUCCESS";
export const PAYMENTS_ADD_VALUES_FAIL = "PAYMENTS_ADD_VALUES_FAIL";
